
#EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
ERROR_INSUFFICIENT_BUFFER =     0x7A;
#FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
HEAP_ZERO_MEMORY        = 0x00000008;
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MEM_COMMIT              =     0x1000;
MEM_FREE                =    0x10000;
MEM_IMAGE               =  0x1000000;
MEM_MAPPED              =    0x40000;
MEM_PRIVATE             =    0x20000;
MEM_RESERVE             =     0x2000;
#NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
#PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PAGE_EXECUTE            =       0x10;
PAGE_EXECUTE_READ       =       0x20;
PAGE_EXECUTE_READWRITE  =       0x40;
PAGE_EXECUTE_WRITECOPY  =       0x80;
PAGE_NOACCESS           =        0x1;
PAGE_READONLY           =        0x2;
PAGE_READWRITE          =        0x4;
PAGE_WRITECOPY          =        0x8;
PROCESS_QUERY_INFORMATION =   0x0400;
PROCESS_VM_OPERATION =        0x0008;
#TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
TOKEN_QUERY             =     0x0008;
TokenIntegrityLevel     =         25;
#UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU
